# Site settings
title: "Biswesh Mohapatra"
email: biswesh.mohapatra@iiitb.org
description: "My Profile"
baseurl: ""
url: "http://carte-noire.jacobtomlinson.co.uk/"
title_description: "I am a second year Engineering student currently undergoing the integrated MTech programme in the field of Computer Science from one of India's top college IIIT-Bangalore."
title_image: "https://i.imgur.com/ExOa8GM.jpg"
google_analytics: "UA-20365477-4"
disqus_account: cartenoire
github_repository: https://github.com/biswesh456/Portfolio
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
github_username:  biswesh456
linkedin_link: https://www.linkedin.com/in/biswesh-mohapatra-199158120/


# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
